### ISSUE TITLE
Update ComCom

### ISSUE THREAD

**Issue by titouan-joseph** [24HeuresINSA/website24maker#8]
# bannière site  
 - [x] changer couleur : #2B3180  
 - [x] changer couleur onglet : #3DA936  
 - [x] changer couleur onglet sélectionné : #E20917  
 - [X] changer logo : “logo site internet”  

# page accueil  
 - [X] enlever la phrase à propos du questionnaire 2019  
   
# Concerts  
 - [x] changer couleur fond : #2B3180  
## artistes  
 - [x] changer couleur nom artistes : #E20917  
 - [X] enlever la phrase “Une grande partie des artistes de l'édition 2020 seront reportés en 2021.”  
## tremplin  
 - [x] “Le Tremplin pour l'édition 2021 aura lieu le 03 mars 2021, les inscriptions sont ouvertes jusqu'à mi-décembre, pour vous inscrire suivez ce lien”  
 - [X] “Le premier tremplin de **l’édition précédente** s’est déroulé le mercredi 18 décembre 2019 et nous avons accueilli 4 artistes et leurs projets : SMAD & the green apple band, Victor Marc et Billet d'Humeur ainsi que Dyfact qui ont terminé la soirée.  
 Pour le second tremplin, nous avons eu la chance de rencontrer le mercredi 15 janvier, toujours au Toï Toï le Zinc : In Balance, Darwells, Bobby Blues Band et Lassanaï.  
 Après une sélection finale difficile, ce sont Billet d'Humeur et Darwells **qui ont été choisi pour partager la** scène des 24h de l’INSA avec les autres artistes programmés.”  
# Courses  
## informations  
 - [x] enlever “EDITION 2020 ANNULEE”  
## FAQ → les courses, c’est quoi, c’est quand ?  
 - [x] enlever “L'édition 2020 est malheureusement annulée.” et remplacer par “L’édition 2021 aura lieu les 22 et 23 mai 2021.”  
# Billetterie  
 - [x] changer couleur fond : #2B3180  
 - [x] changer couleur décompte + texte : #E20917  
 - [x] enlever les 3 bandeaux de couleur  
# Infos pratiques  
## Comment payer  
 - [x] Enlever le “ou Lyfpay” dans “COMMENT PAYER ? Espèce, CB ou Lyf Pay, c'est vous qui voyez”  
## Transports  
 - [ ] changer couleur titre (“en train” etc) : #2B3180  
 - [ ] changer typo titre pour “millimetre”

**Comment by titouan-joseph** [comment]
Pour la page des transports, c'est sur l'image les changements
Elsa va peut-etre regarder de les refaire
